# Generated by Django 2.1.3 on 2019-06-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stress_db',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SRP_ID', models.CharField(blank=True, max_length=200)),
                ('SRR_ID', models.CharField(blank=True, max_length=200)),
                ('Assay_Type', models.CharField(blank=True, max_length=200)),
                ('Cultivar', models.CharField(blank=True, max_length=200)),
                ('Treatment', models.CharField(blank=True, max_length=200)),
                ('Stage', models.CharField(blank=True, max_length=200)),
                ('Tissue', models.CharField(blank=True, max_length=200)),
                ('Layout', models.CharField(blank=True, max_length=200)),
                ('Gene_ID', models.CharField(blank=True, max_length=200)),
                ('TPM', models.CharField(blank=True, max_length=200)),
                ('Treat', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'Stress_db',
            },
        ),
    ]
