# Generated by Django 2.1.3 on 2019-06-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SRP_ID', models.CharField(blank=True, max_length=200)),
                ('SRR_ID', models.CharField(blank=True, max_length=200)),
                ('Assay_Type', models.CharField(blank=True, max_length=200)),
                ('Cultivar', models.CharField(blank=True, max_length=200)),
                ('Treatment', models.CharField(blank=True, max_length=200)),
                ('Stage', models.CharField(blank=True, max_length=200)),
                ('Tissue', models.CharField(blank=True, max_length=200)),
                ('Layout', models.CharField(blank=True, max_length=200)),
                ('Gene_ID', models.CharField(blank=True, max_length=200)),
                ('TPM', models.CharField(blank=True, max_length=200)),
                ('Treat', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'leaf',
            },
        ),
        migrations.CreateModel(
            name='M_leaf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SRP_ID', models.CharField(blank=True, max_length=200)),
                ('SRR_ID', models.CharField(blank=True, max_length=200)),
                ('Assay_Type', models.CharField(blank=True, max_length=200)),
                ('Cultivar', models.CharField(blank=True, max_length=200)),
                ('Treatment', models.CharField(blank=True, max_length=200)),
                ('Stage', models.CharField(blank=True, max_length=200)),
                ('Tissue', models.CharField(blank=True, max_length=200)),
                ('Layout', models.CharField(blank=True, max_length=200)),
                ('Gene_ID', models.CharField(blank=True, max_length=200)),
                ('TPM', models.CharField(blank=True, max_length=200)),
                ('Treat', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'M_leaf',
            },
        ),
        migrations.CreateModel(
            name='R_leaf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SRP_ID', models.CharField(blank=True, max_length=200)),
                ('SRR_ID', models.CharField(blank=True, max_length=200)),
                ('Assay_Type', models.CharField(blank=True, max_length=200)),
                ('Cultivar', models.CharField(blank=True, max_length=200)),
                ('Treatment', models.CharField(blank=True, max_length=200)),
                ('Stage', models.CharField(blank=True, max_length=200)),
                ('Tissue', models.CharField(blank=True, max_length=200)),
                ('Layout', models.CharField(blank=True, max_length=200)),
                ('Gene_ID', models.CharField(blank=True, max_length=200)),
                ('TPM', models.CharField(blank=True, max_length=200)),
                ('Treat', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'R_leaf',
            },
        ),
        migrations.CreateModel(
            name='root',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SRP_ID', models.CharField(blank=True, max_length=200)),
                ('SRR_ID', models.CharField(blank=True, max_length=200)),
                ('Assay_Type', models.CharField(blank=True, max_length=200)),
                ('Cultivar', models.CharField(blank=True, max_length=200)),
                ('Treatment', models.CharField(blank=True, max_length=200)),
                ('Stage', models.CharField(blank=True, max_length=200)),
                ('Tissue', models.CharField(blank=True, max_length=200)),
                ('Layout', models.CharField(blank=True, max_length=200)),
                ('Gene_ID', models.CharField(blank=True, max_length=200)),
                ('TPM', models.CharField(blank=True, max_length=200)),
                ('Treat', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'root',
            },
        ),
        migrations.RenameModel(
            old_name='stress_db',
            new_name='A_shoot',
        ),
        migrations.AlterModelTable(
            name='a_shoot',
            table='A_shoot',
        ),
    ]
