# Generated by Django 2.1.3 on 2019-06-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190616_1504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='R_leaf',
            new_name='Stress_db',
        ),
        migrations.DeleteModel(
            name='A_shoot',
        ),
        migrations.DeleteModel(
            name='leaf',
        ),
        migrations.DeleteModel(
            name='M_leaf',
        ),
        migrations.DeleteModel(
            name='root',
        ),
        migrations.AlterModelTable(
            name='stress_db',
            table='Stress_db',
        ),
    ]
