# Generated by Django 2.1.3 on 2019-06-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190616_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SRP_ID', models.CharField(blank=True, max_length=200)),
                ('SRR_ID', models.CharField(blank=True, max_length=200)),
                ('Assay_Type', models.CharField(blank=True, max_length=200)),
                ('Cultivar', models.CharField(blank=True, max_length=200)),
                ('Treatment', models.CharField(blank=True, max_length=200)),
                ('Stage', models.CharField(blank=True, max_length=200)),
                ('Tissue', models.CharField(blank=True, max_length=200)),
                ('Layout', models.CharField(blank=True, max_length=200)),
                ('Treat', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'Description',
            },
        ),
        migrations.DeleteModel(
            name='A_shoot',
        ),
        migrations.DeleteModel(
            name='leaf',
        ),
        migrations.DeleteModel(
            name='M_leaf',
        ),
        migrations.DeleteModel(
            name='R_leaf',
        ),
        migrations.DeleteModel(
            name='root',
        ),
    ]
