# Generated by Django 2.1.3 on 2019-06-20 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190620_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='Assay_Type',
        ),
        migrations.RemoveField(
            model_name='description',
            name='Cultivar',
        ),
        migrations.RemoveField(
            model_name='description',
            name='Layout',
        ),
        migrations.RemoveField(
            model_name='description',
            name='SRP_ID',
        ),
        migrations.RemoveField(
            model_name='description',
            name='SRR_ID',
        ),
        migrations.RemoveField(
            model_name='description',
            name='Stage',
        ),
        migrations.RemoveField(
            model_name='description',
            name='Tissue',
        ),
        migrations.RemoveField(
            model_name='description',
            name='Treat',
        ),
        migrations.RemoveField(
            model_name='description',
            name='Treatment',
        ),
    ]
