# Generated by Django 2.1.3 on 2019-06-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190620_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tpm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Tpm',
            },
        ),
        migrations.AddField(
            model_name='description',
            name='Assay_Type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='description',
            name='Cultivar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='description',
            name='Layout',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='description',
            name='SRP_ID',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='description',
            name='SRR_ID',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='description',
            name='Stage',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='description',
            name='Tissue',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='description',
            name='Treat',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='description',
            name='Treatment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
