# Generated by Django 2.1.3 on 2019-06-21 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190620_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tpm',
        ),
    ]
