# Generated by Django 2.1.3 on 2019-06-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_tpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='tpm_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_id', models.CharField(blank=True, max_length=200)),
                ('Tpm', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'tpm_list',
            },
        ),
    ]
