# Generated by Django 2.1.3 on 2019-06-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_tpm_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tpm_list',
            name='Tpm',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
